general.live_config_reload = true

# Flow colorscheme | Alacritty
# https://github.com/0xstepit/flow.nvim

# Black and white
[colors.primary]
background = '#1b2228'
foreground = '#b3c1cc'

# Normal colors
[colors.normal]
black = '#0d0d0d'
red = '#d98c93'
green = '#93d98c'
yellow = '#d9d28c'
blue = '#8cb9d9'
magenta = '#ac8cd9'
cyan = '#8cd9d2'
white = '#f2f2f2'

# Bright colors
[colors.bright]
black = '#0d0d0d'
red = '#d98c93'
green = '#93d98c'
yellow = '#d9d28c'
blue = '#8cb9d9'
magenta = '#ac8cd9'
cyan = '#8cd9d2'
white = '#f2f2f2'

# Search colors
[colors.search.matches]
foreground = '#ff007b'
background = '#0d0d0d'

[colors.search.focused_match]
foreground = '#0d0d0d'
background = '#ff007b'

# Selection colors
[colors.selection]
background = '#ff007b'
text = '#0d0d0d'

# Cursors
# If you don't want to override original behavior, which is nice,
# remove [colors.cursor] and [colors.vi_mode_cursor].
# [colors.cursor]
# cursor = '#ff007b'
# text = '#0d0d0d'
#
# [colors.vi_mode_cursor]
# cursor = '#ff007b'
# text = '#0d0d0d'

[colors.footer_bar]
foreground = '#ff007b'
background = '#0d0d0d'

[[colors.indexed_colors]]
index = 93
color = '#ac8cd9'

# Fluo Colors
[[colors.indexed_colors]]
index = 198
color = '#ff007b'


[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14

[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.95
# startup_mode = "Fullscreen"
