window:
  opacity: 0.95

font:
  normal:
    family: FantasqueSansM Nerd Font
    style: Regular

  bold:
    family: FantasqueSansM Nerd Font
    style: Bold

  italic:
    family: FantasqueSansM Nerd Font
    style: Italic

  bold_italic:
    family: FantasqueSansM Nerd Font
    style: Bold Italic

  size: 11
  
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true
