window:
  decorations: none
  opacity: 0.97
  
font:
  size: 11

env:
  TERM: xterm-256color
  
# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'
  save_to_clipboard: true

live_config_reload: true

